[package]
name = "relativedelta"
version = "0.1.0"
authors = ["Tim Gorm Kaas-Rasmussen Olsen <timgormkaas@gmail.com>"]
edition = "2018"
license = "MPL-2.0+"
homepage = "https://github.com/timkaas/relativedelta/"
repository = "https://github.com/timkaas/relativedelta/"
documentation = "./README.md"
description = """
Rust implementation of relativedelta known from Python's dateutil
"""

[dependencies]
chrono = { version = "^0.4"}
impl_ops = "^0.1"
num-integer = "^0.1"

#serde = {version = "1.0", optional = true}

[dependencies.serde]
package = "serde"
optional = true
version = "1.0.89"
default-features = false

[dev-dependencies.serde_derive]
version = "1"
default-features = false

[dev-dependencies.serde_json]
version = "1"
